### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by jwinarske**
**CMake support**
- When building the upper layer project, you need all the toolchains in your path, or it will fail...
- I created a host target, which is generic for all hosts.  You may want to consider removing "x86_64-w64-mingw32".

**Win64 Native / Host Build / Visual Studio**
real-time-cpp\build>cmake ..\ref_app -DTARGET=host
real-time-cpp\build>cmake --build . --config Debug --target INSTALL

**Linux Native / Host Build**
real-time-cpp$ mkdir build_linux_host && cd build_linux_host
real-time-cpp$ cmake ../ref_app -DTRIPLE=x86_64-linux-gnu -DTARGET=host -DCMAKE_TOOLCHAIN_FILE=../ref_app/cmake/gcc-toolchain.cmake
real-time-cpp$ make -j7

**Linux w64-mingw32 / Host Build**
real-time-cpp$ mkdir build_w64_mingw32 && cd build_w64_mingw32
real-time-cpp$ cmake ../ref_app -DTRIPLE=x86_64-w64-mingw32 -DTARGET=host -DCMAKE_TOOLCHAIN_FILE=../ref_app/cmake/gcc-toolchain.cmake
real-time-cpp$ make -j7

**Linux Upper Layer / All projects**
real-time-cpp$ mkdir build && cd build
real-time-cpp$ cmake ..
real-time-cpp$ time make -j7
...
real 0m16.815s
user 1m30.496s
sys 0m8.878s

**Using Visual Studio to build All Projects**
real-time-cpp$ mkdir build && cd build
real-time-cpp$ cmake ..
real-time-cpp$ cmake --build . --config Debug --target INSTALL

The basic requirements are:
1.  TRIPLE and/or TARGET variables come before the toolchain file
2.  The build folder can be located anywhere

Type "cmake -G" on build host to see available projects one can target.

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi Joel. Thanks for moving forward on the CMake builds. I am really swamped w´right now so it might take 2 or 3 days until I get a chance to merge to master. It looks like there are no merge conflicts, but I would still like to take a day or so to look at the progress, OK? Bset regards, Chris

**Comment by jwinarske** [comment]
No worries.  A few more changes, and once I remove the note **not complete**, I'm ready.

**Comment by ckormanyos** [comment]
It looks good, Joel.
Could you please indicate when I should go for merging the PR?

**Comment by jwinarske** [comment]
Anytime!

**Comment by gdobato** [comment]
Hello,
Really nice work!
I tested the target stm32f429 on Debian10/Toolchain: gcc-arm-none-eabi-8-2019-q3-update.
LedBlinky working on my side.

[Log]
(...)
gdobato@unix:~/Workspace/test/real-time-cpp/build_linux_host$ cmake ../ref_app -DTRIPLE=arm-none-eabi -DTARGET=stm32f429 -DCMAKE_TOOLCHAIN_FILE=../ref_app/cmake/gcc-toolchain.cmake
gdobato@unix:~/Workspace/test/real-time-cpp/build_linux_host$ make -j
(...)
_[ 97%] Building CXX object CMakeFiles/ref_app.dir/target/micros/stm32f429/startup/int_vect.cpp.obj
[100%] Linking CXX executable ref_app.elf
Generating Post Build Artifacts
[100%] Built target ref_app
gdobato@unix:~/Workspace/test/real-time-cpp/build_linux_host$ ls
CMakeCache.txt       ref_app.bin          ref_app.lss          ref_app_size.txt
CMakeFiles           ref_app_cppfilt.txt  ref_app.map
cmake_install.cmake  ref_app.elf          ref_app_nm.txt
Makefile             ref_app.hex          ref_app_readelf.txt
gdobato@unix:~/Workspace/test/real-time-cpp/build_linux_host$ st-flash --format ihex write ref_app.hex
st-flash 1.5.1-50-g3690de9
2019-11-27T00:46:54 INFO common.c: Loading device parameters....
2019-11-27T00:46:54 INFO common.c: Device connected is: F42x and F43x device, id 0x20016419
2019-11-27T00:46:54 INFO common.c: SRAM size: 0x40000 bytes (256 KiB), Flash: 0x200000 bytes (2048 KiB) in pages of 16384 bytes
2019-11-27T00:46:54 INFO common.c: Attempting to write 3028 (0xbd4) bytes to stm32 address: 134217728 (0x8000000)
Flash page at addr: 0x08000000 erased
2019-11-27T00:46:55 INFO common.c: Finished erasing 1 pages of 16384 (0x4000) bytes
2019-11-27T00:46:55 INFO common.c: Starting Flash write for F2/F4/L4
2019-11-27T00:46:55 INFO flash_loader.c: Successfully loaded flash loader in sram
enabling 32-bit flash writes
size: 3028
2019-11-27T00:46:55 INFO common.c: Starting verification of write complete
2019-11-27T00:46:55 INFO common.c: Flash written and verified! jolly good!_

**Comment by ckormanyos** [comment]
Thank you gdobato for verifying one of the CMake builds.

**Comment by ckormanyos** [comment]
Great work, Joel. Thank you for creating CMake builds.

**Comment by jwinarske** [comment]
Thanks, and you're welcome!

**Pull request merged**
