### PR TITLE
Set execute permissions for bash scripts on unix

### PR DESCRIPTION
**Pull request by mark-1003**
As mentioned in ticket:
https://github.com/ckormanyos/real-time-cpp/issues/55

### CODE REVIEW

**Comment by fivdi** [comment]
The PR works for me on Linux.
```
$ git clone https://github.com/mark-1003/real-time-cpp.git
Cloning into 'real-time-cpp'...
remote: Enumerating objects: 823, done.
remote: Counting objects: 100% (823/823), done.
remote: Compressing objects: 100% (329/329), done.
remote: Total 15605 (delta 487), reused 701 (delta 467), pack-reused 14782
Receiving objects: 100% (15605/15605), 166.54 MiB | 5.78 MiB/s, done.
Resolving deltas: 100% (10413/10413), done.
Checking connectivity... done.
$ cd real-time-cpp/
$ git checkout bugfix/set-execute-permissions-for-bash-scripts
Branch bugfix/set-execute-permissions-for-bash-scripts set up to track remote branch bugfix/set-execute-permissions-for-bash-scripts from origin.
Switched to a new branch 'bugfix/set-execute-permissions-for-bash-scripts'
$ cd examples/chapter02_02/
$ ls -la
total 84
drwxrwxr-x  3 brian brian  4096 Jun 14 12:20 .
drwxrwxr-x 16 brian brian  4096 Jun 14 12:20 ..
-rw-rw-r--  1 brian brian  1826 Jun 14 12:20 avr.ld
drwxrwxr-x  2 brian brian  4096 Jun 14 12:20 bin
-rw-rw-r--  1 brian brian  1771 Jun 14 12:20 build.bat
-rwxrwxr-x  1 brian brian  2570 Jun 14 12:20 build.sh
-rw-rw-r--  1 brian brian   953 Jun 14 12:20 chapter02_02.atsln
-rw-rw-r--  1 brian brian 10373 Jun 14 12:20 chapter02_02.cppproj
-rw-rw-r--  1 brian brian   771 Jun 14 12:20 chapter02_02.sln
-rw-rw-r--  1 brian brian  2879 Jun 14 12:20 chapter02_02.vcxproj
-rw-rw-r--  1 brian brian  1056 Jun 14 12:20 chapter02_02.vcxproj.filters
-rw-rw-r--  1 brian brian  3921 Jun 14 12:20 CMakeLists.txt
-rw-rw-r--  1 brian brian  2476 Jun 14 12:20 crt0.s
-rw-rw-r--  1 brian brian  1575 Jun 14 12:20 cstdint
-rw-rw-r--  1 brian brian   635 Jun 14 12:20 flash.txt
-rw-rw-r--  1 brian brian     5 Jun 14 12:20 .gitignore
-rw-rw-r--  1 brian brian  1725 Jun 14 12:20 led.cpp
-rw-rw-r--  1 brian brian   916 Jun 14 12:20 mcal_reg.h
-rw-rw-r--  1 brian brian  2863 Jun 14 12:20 readme.md
$ ./build.sh 

Building with        : build.sh
Using tool path      : /home/brian/opt/arduino-1.8.10/hardware/tools/avr/bin
Using tool prefix    : avr
Remove bin directory : bin/
Create bin directory : bin/

Assemble : crt0.s  to bin/crt0.o
Compile  : led.cpp to bin/led.o
Link     : objects to bin/led.elf

Extract  : executalbe hex file : from bin/led.elf
Extract  : assembly list file  : from bin/led.elf
Extract  : size information    : from bin/led.elf
Extract  : name information    : from bin/led.elf
Extract  : demangled names     : from bin/led.elf
$ 
```
```
$ cd ../chapter04_04
$ ls -la
total 144
drwxrwxr-x  5 brian brian  4096 Jun 14 12:20 .
drwxrwxr-x 16 brian brian  4096 Jun 14 12:20 ..
-rw-rw-r--  1 brian brian  5966 Jun 14 12:20 build.bat
-rwxrwxr-x  1 brian brian  6498 Jun 14 12:20 build.sh
-rw-rw-r--  1 brian brian   949 Jun 14 12:20 chapter04_04.atsln
-rw-rw-r--  1 brian brian 21897 Jun 14 12:20 chapter04_04.cppproj
-rw-rw-r--  1 brian brian  1624 Jun 14 12:20 chapter04_04.sln
-rw-rw-r--  1 brian brian 33029 Jun 14 12:20 chapter04_04.vcxproj
-rw-rw-r--  1 brian brian 18877 Jun 14 12:20 chapter04_04.vcxproj.filters
drwxrwxr-x  2 brian brian  4096 Jun 14 12:20 images
-rw-rw-r--  1 brian brian  3604 Jun 14 12:20 readme.md
drwxrwxr-x 11 brian brian  4096 Jun 14 12:20 src
drwxrwxr-x  4 brian brian  4096 Jun 14 12:20 target
-rw-rw-r--  1 brian brian 11813 Jun 14 12:20 target.vcxproj
-rw-rw-r--  1 brian brian  2315 Jun 14 12:20 target.vcxproj.filters
$ 
```

**Comment by ckormanyos** [comment]
Fixes #55

**Comment by ckormanyos** [comment]
> As mentioned in ticket:

Thank you.
Kind regards, Chris

**Comment by ckormanyos** [comment]
For the purposes or remembering how to do this, see image below
chmod

**Pull request merged**
