### PR TITLE
Work repo badges and test app benchmarks emulator.py

### PR DESCRIPTION
**Pull request by imahjoub**
Hi @ckormanyos,

In this pull request I made two changes:

- badges alignment.
- handled the return value of benchmark emulator script.

**regarding point 2:**
I created a function def [ check_ret_value](https://github.com/imahjoub/real-time-cpp/blob/ef78410b259cb39ed3afc4ffbb3dbaf9d05a68be/ref_app/target/build/test_app_benchmarks_emulator.py#L27) is checking the gdb return value. I could not work with hex values because for some reason the program crashed when I converted the return value of gdb to hex, but it did work with the conversion to string. 

**Note:** 
the return type of [parse_and_eval](https://github.com/imahjoub/real-time-cpp/blob/ef78410b259cb39ed3afc4ffbb3dbaf9d05a68be/ref_app/target/build/test_app_benchmarks_emulator.py#L56) is "gdb.Value"

conversion:
gdb.value -> string (works fine)
gdb.value -> hex    (does not work, I will check later for that.)

thanks and kind regards, Iliass

### CODE REVIEW

**Comment by ckormanyos** [comment]
Thanks for looking into this @imahjoub.

As a first-time contributor, I needed to approve your workflow run. Let's see how CI rolls through...

**Comment by ckormanyos** [comment]
Thanks @imahjoub I just started up CI and temporarily removed the Sonar branch requirements.

Let's see how this runs through. The code looks really good.

**Comment by imahjoub** [comment]
Hi @ckormanyos,

can you please re-run the jobs again, I had to delete some "print" cmds. Now I'm finished.
The hash of my last commit is [8091849](https://github.com/ckormanyos/real-time-cpp/pull/278/commits/8091849167de59da0afe10874e3820a400bb8195).

**Comment by ckormanyos** [comment]
Hi Iliass (@imahjoub) actually, I think we can simply re-open this PR.

You simply need to restore all of the CI jobs in YAML, then we can see how it runs.

The QEMU jobs are running. Sonar has been removed from branch protectoin. So when all of CI is restored, we should expect a green run.

**Comment by ckormanyos** [comment]
Hi Iliass (@imahjoub) thanks for providing this inspiration and improvement.

I reworked some of your Python and YAML. There are a couple of finer YAML and Python pretty-printing points you might like to handle. Feel free to either re-open this PR or create a new one any time.

Thanks again for this improvement.

**Pull request merged**
