### PR TITLE
CMake support for AppleClang

### PR DESCRIPTION
**Pull request by jwinarske**
Adds support for building "host" for MacOS via Terminal window using AppleClang.

```
cd real-time-cpp
mkdir build
cd build
cmake ../ref_app -DTARGET=host
make install -j8
```

### CODE REVIEW

**Comment by ckormanyos** [comment]
Thank you for adding support for building "host" for MacOS via Terminal window using AppleClang.

**Comment by ckormanyos** [comment]
Hi @jwinarske just for your info, it has been two years, but just for your info, several of your fantastic and beautiful CMake builds are now running in on Ubuntu pipelines in CI on GitHub actions.

Thanks again for providing this technology.

**Comment by jwinarske** [comment]
@ckormanyos Cool!  Thanks for the kind words, and thanks for the inspirational book 👍

**Comment by ckormanyos** [comment]
> Cool! Thanks for the kind words, and thanks for the inspirational book

Thank you as well. It is good to hear your kind response. Progress is ongoing, as I intend to also integrate some `macos` builds and builds for the examples as time allows. I am also strongly considering to try to figure out how to get an AVR(R) and/or ARM(R) simulators on a test runner in the future to do some actual target-based simulations...

**Comment by jwinarske** [comment]
[This](https://lowenware.com/blog/osdev/aarch64-bare-metal-program-in-rust/) covers most everything on using QEMU for aarch64 bare metal.  ARMv7, and QEMU AVR would follow the same pattern.  CTest could be used to execute the unit tests; minor CMake changes.  It might make sense to use a binary repository (Conan or other) to manage toolchains, and QEMU flavors.  Then maybe add some stack trace capture.

**Comment by ckormanyos** [comment]
> ... covers most everything on using QEMU for aarch64 bare metal. ARMv7, and QEMU AVR would follow the same pattern. CTest could be used to execute the unit tests; minor CMake changes.

Thank you for this very good idea, Joel. Sounds like a plan! And will pursue this further in #96.

**Pull request merged**
